import React from 'react';
import { ShieldAlert, CheckCircle2, AlertTriangle, Cpu, Layers, Radio, X } from 'lucide-react';
import { useParking } from '../../context/ParkingContext';

export const DemoModal: React.FC = () => {
  const { isDemoModalOpen, setIsDemoModalOpen, systemMode } = useParking();

  if (!isDemoModalOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-2xl bg-slate-900 border border-slate-700/80 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-900/90">
          <div className="flex items-center gap-3">
            <span className="inline-flex items-center justify-center p-2 rounded-lg bg-amber-500/10 text-amber-400 border border-amber-500/20">
              <ShieldAlert className="w-5 h-5" />
            </span>
            <div>
              <h2 className="text-base sm:text-lg font-bold text-white tracking-tight">
                Academic Integrity & Subsystem Transparency
              </h2>
              <p className="text-xs text-slate-400">Review 2 Engineering Audit Disclosure</p>
            </div>
          </div>
          <button
            onClick={() => setIsDemoModalOpen(false)}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
            aria-label="Close modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto space-y-5 text-sm text-slate-300">
          <div className="p-4 rounded-xl bg-amber-950/20 border border-amber-500/30 text-amber-200 text-xs leading-relaxed">
            <strong>Truthfulness & Honesty Mandate:</strong> ParkSight AI is an academic systems prototype for college review. We strictly distinguish between what is genuinely functional, what runs on real computer vision, and what is generated by our deterministic state simulation engine.
          </div>

          {/* Status Model Matrix */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-slate-200 uppercase tracking-wider">Subsystem Status Classification</h3>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
              <div className="p-2.5 rounded-xl bg-emerald-950/40 border border-emerald-500/30">
                <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                  REAL
                </span>
                <p className="text-[11px] text-slate-300 mt-1.5 font-medium">Image/Video Ingest &amp; Pixel CV</p>
                <p className="text-[10px] text-slate-400 mt-0.5">Real canvas frame processing, bounding box generation, and IoU polygon evaluation.</p>
              </div>

              <div className="p-2.5 rounded-xl bg-cyan-950/40 border border-cyan-500/30">
                <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-cyan-500/20 text-cyan-300 border border-cyan-500/40">
                  SIMULATED
                </span>
                <p className="text-[11px] text-slate-300 mt-1.5 font-medium">Digital Twin Deck</p>
                <p className="text-[10px] text-slate-400 mt-0.5">Mulberry32 PRNG traffic dynamics, diurnal curves, and 3-frame temporal state machine.</p>
              </div>

              <div className="p-2.5 rounded-xl bg-purple-950/40 border border-purple-500/30">
                <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-purple-500/20 text-purple-300 border border-purple-500/40">
                  PROTOTYPE
                </span>
                <p className="text-[11px] text-slate-300 mt-1.5 font-medium">Recommendations &amp; Forecast</p>
                <p className="text-[10px] text-slate-400 mt-0.5">Heuristic 100-pt objective function score and Holt's double exponential smoothing.</p>
              </div>

              <div className="p-2.5 rounded-xl bg-slate-900 border border-slate-700">
                <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-slate-800 text-slate-400 border border-slate-700">
                  FUTURE
                </span>
                <p className="text-[11px] text-slate-300 mt-1.5 font-medium">Production Hardware</p>
                <p className="text-[10px] text-slate-400 mt-0.5">NVIDIA Jetson Orin edge appliance, RTSP PoE cameras, and BLE indoor localization.</p>
              </div>
            </div>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-800/40 border border-slate-800 space-y-1.5 text-xs">
            <div className="flex items-center gap-2 text-white font-medium">
              <Cpu className="w-4 h-4 text-cyan-400" />
              <span>Current Operating Mode: <span className="font-mono text-cyan-300">{systemMode}</span></span>
            </div>
            <p className="text-slate-400 leading-relaxed text-[11px]">
              When you upload an image or video frame in the CV Workspace and click <strong className="text-slate-200">"Propagate to Live State"</strong>, real detections immediately update parking bays, triggering live events, alerts, and navigation updates.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-3.5 border-t border-slate-800 bg-slate-900/90 flex justify-end">
          <button
            onClick={() => setIsDemoModalOpen(false)}
            className="px-4 py-2 text-xs font-semibold text-white bg-cyan-600 hover:bg-cyan-500 rounded-lg transition-colors shadow-sm"
          >
            Acknowledge &amp; Continue
          </button>
        </div>
      </div>
    </div>
  );
};
